"""Add image_url property to Card model

Revision ID: 5b58cb15d1cf
Revises: d49ab7ebc463
Create Date: 2025-07-09 08:38:38.492411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b58cb15d1cf'
down_revision = 'd49ab7ebc463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
