"""empty message

Revision ID: b64526905550
Revises: 27ca81b2702b
Create Date: 2025-06-24 11:19:05.358315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64526905550'
down_revision = '27ca81b2702b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('board_id')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_constraint('card_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])
        batch_op.drop_column('card_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('card_board_id_fkey', 'board', ['board_id'], ['board_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.INTEGER(), server_default=sa.text("nextval('board_board_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
